### ISSUE TITLE
Jetclient at android

### ISSUE THREAD

**Issue by nikolaykuz** [menacher/java-game-server#31]
Please, let us know whether it is possible to use jetclient for android app, and if not what kind of modifications would be necessary.  Thank

**Comment by navodit-nit** [comment]
Hi menacher, I tried to get into root of the issue, Android doesnt have all classes in its nio package. which are there in use in jetclient.

**Comment by menacher** [comment]
Oh ok. Do you know specifically which classes are missing. I could try to remove those. Also which version of Android?
